# 站点基本信息
title: itaken's pages
keyword: "itaken, 博客, 个人网站, 互联网, 前端, 后端, PHP, vue"
description: "记笔记,记笔记,记笔记"
baseurl: "" # the subpath of your site, e.g. /blog
logo: assets/images/logo.jpg
url: "https://itaken.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
tag_url: "/dish/tags.html"

# 个人信息
email: "regelhh@gmail.com"
github_username:  itaken
github_avatar: https://avatars3.githubusercontent.com/u/2723658?v=3&s=120

# Build settings
timezone: Asia/Shanghai
encoding: utf-8
highlighter: rouge

# Markdown settings
markdown: kramdown
kramdown:
    input: GFM

sass:
    sass_dir: _sass
    style: compressed

exclude: ["node_modules","Gruntfile.js","package.json","README.md","Gemfile","Gemfile.lock"]
anchorjs: true

# Pagination
permalink: pretty
paginate: 10
paginate_path: "blog/page:num/"

# Gems
gems: [jekyll-paginate, jekyll-gist]
