# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: itaken's pages
email: ""
description: 总想留下点什么,记忆太短暂,罢了,记录下来吧.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itaken.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
tag_url: "/dish/tags.html"
github_username:  itaken
github_avatar: https://avatars3.githubusercontent.com/u/2723658?v=3&s=120
timezone: Asia/Shanghai
encoding: utf-8
# Build settings
markdown: kramdown

# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
# incremental: false

#theme: default # minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock

# Pagination
paginate: 5
paginate_path: "pages/:num/"

#permalink: /:categories/:year/:month/:day/:title.html

sass:
    sass_dir: _sass
    style: compressed
